from pathlib import Path
import re

ARCHETYPE_ROOT = Path("arquetipo-storage-consumidor")
OUTPUT_DIR = Path("generated")
OUTPUT_DIR.mkdir(exist_ok=True)


DEFAULT_VARIABLES = [
    "environment",
    "criticality",
    "workload",
    "owner",
]


def discover_variables():

    vars_files = list(ARCHETYPE_ROOT.rglob("variables.tf"))

    if vars_files:
        content = vars_files[0].read_text(encoding="utf-8")
        variables = re.findall(r'variable\\s+"([^"]+)"', content)

        if variables:
            return variables

    tf_files = list(ARCHETYPE_ROOT.rglob("*.tf"))

    for tf in tf_files:
        content = tf.read_text(encoding="utf-8")
        variables = re.findall(r'variable\\s+"([^"]+)"', content)

        if variables:
            return variables

    return DEFAULT_VARIABLES


def generate_tfvars(entities):

    variables = discover_variables()

    values = {
        "environment": entities.get("environment", "dev"),
        "criticality": entities.get("criticality", "low"),
        "workload": entities.get("workload", "logs"),
        "owner": entities.get("owner", "cloud-governance-agent"),
    }

    output = OUTPUT_DIR / "terraform.auto.tfvars"

    with output.open("w", encoding="utf-8") as f:

        f.write("# Generated by Cloud Governance Agent\n\n")

        for var in variables:
            value = values.get(var, "TODO")
            f.write(f'{var} = "{value}"\n')

    return output